# Group API 修改记录

在这里写每次API修改的内容。
## 2016年10月25日
1.新增三个接口(新建学科群需要填写类型，学段，学科)<br />
    - <a href="#群组设置-获取新建学科群是选择群类型-get">获取新建学科群是选择群类型</a><br />
    - <a href="#群组设置-获取新建学科群是选择群学段-get">获取新建学科群是选择群学段</a><br />
    - <a href="#群组设置-获取新建学科群是选择群学科-get">获取新建学科群是选择群学科</a>

## 2016年10月27日
1.漏了修改三个老接口(获取动态，获取动态详情，获取指定动态的评论，需要返回相关平路你的图片)<br />
    - <a href="#修改之前的接口-获取全部动态-get">获取全部动态</a><br />
    - <a href="#修改之前的接口-获取指定动态id的详情-get">获取指定动态id的详情</a><br />
    - <a href="#群组设置-获取指定动态的评论-get">获取指定动态的评论</a>

## 2016年10月31日
1.新增两个接口(资源点赞和删除)<br />
    - <a href="#群组资源-点赞某个资源-post">点赞某个资源</a><br />
    - <a href="#群组资源-删除某个资源-delete">删除某个资源</a><br />
2.修改创建群组接口,区管理员创建一个群的时候和指定群主和群管理员,删除获取群类型的接口(可写死)<br />
    - <a href="#群组设置-新建群-post">新建群</a><br />

## 2016年11月01日
1.修改接口，返回用户信息，添加返回学校id<br />
    - <a href="#修改之前的接口-返回当前用户信息-get">返回当前用户信息</a><br />
2.新增接口，上传群组头像<br/>
    - <a href="#群组设置-上传群头像-post">上传群头像</a><br />
3.合并设置管理员和取消管理员接口
    - <a href="#群组成员-移除管理员-添加管理员-post">设置管理员</a><br />
## 2016年11月02日
1.修改接口，返回群组基本信息,判断角色<br />
    - <a href="#群组设置-获取群组基本信息-get">获取群组基本信息</a><br />
## 2016年11月03日
1.修改接口，发表动态,和发表话题，发表群组动态，发表话题发言统一使用<br />
    - <a href="#修改之前的接口-发表动态-话题-post">发表动态-话题</a><br />
2.所有有关权限操作都使用role(1:群主,2:管理员,3:普通成员,4:不是本群成员)<br />

## 2016年12月12日
1.修改接口，获取动态和动态详情，添加附件下载功能和视频播放功能<br />
2.群组资源增加视频播放功能<br />
3.获取群组基本信息添加群组背景图片字段
