# Group 修改之前的接口

## 返回当前用户信息 [GET /who]
这个接口之前就有，现在修改，返回此用户的角色(系统管理员，校管理员，普通成员)

+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + id: `12312312`(string,required) - 当前用户的id
        + username: `zhourunfa`(string,required) - 当前用户登录的用户名
        + name: `周润发`(string,required) - 当前用户的名字
        + school: `乐知行学校`(string,required) - 当前用户所在学校
        + school_id: `31231`(string,required) - 当前用户所在学校id
        + profile_image_url: `http:www.baidu.com/xxx.jpg`(string,required) - 当前用户头像
        + type(enum,required) - 用户角色判断(1:系统管理员,2:区管理员,3:校管理员,4:普通教师)
            + Members
                + 1(number,required)
                + 2(number,required)
                + 3(number,required)
                + 4(number,required)

## 发表评论 [POST /feeds/{id}/comments]

修改之前的接口，需要评论可以带图片

+ Parameters
    + id: `112121212`(string,required) - 群组的id

+ Request (application/json;charset=utf-8)
    + Attributes
        + postFile: `12312312:xxx.png|`(string,required) - 评论动态时上传的图片(评论只能一张图片)
        + replyId: `131231`(string,required) - 回复的id,如果没有代表直接回复该条动态
        + text: `霹雳哗啦评论内容啊啊啊啊`(string,required) - 评论的内容

+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 移除是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息


## 获取全部动态 [GET /feeds{?page,per_page}]

这是个人页面的接口，获取动态评论的时候需要返回图片信息,
2016年12月06日, 再次修改, 增加视频在线播放功能

+ Parameters
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + total_count: 100 (number,required) - 数据总数
        + data(array[object], fixed) - 所有动态
            + (object)
                + id: `123456` (string,required) - 动态id
                + comments(object,required) - 动态评论数组(目前在首页只显示三条，详情中全部显示)
                    + total_count: 100 (number,required) - 所有动态评论总数
                    + data (array[object],fixed) - 动态评论的前三条
                        + (object)
                            + id: `9890`(string,required) - 评论id
                            + user(object,required) - 评论人的信息obj
                                + id: `231123`(string,required) - 评论人的id
                                + name: `周润发`(string,required) - 评论人的name
                                + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                            + reply(object,required) - 评论回复人信息obj
                                + id: `765665`(string,required) - 评论回复人的id
                                + name: `赌神`(string,required) - 评论回复人的名字
                            + created_at: `12秒前`(string,required) - 评论时间
                            + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                            + pics(array[object],fixed) - 评论图片或回复图片数组
                                + (object)
                                    + name: `xxx`(string,required) - 评论图片或回复图片名字1
                                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + user(object,required) - 动态发表人信息对象
                    + id: `1111` (string,required) - 动态发表人id
                    + name: `王小二` (string,required) - 动态发表人name
                    + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
                + created_at: `10月18日 20:14` (string,required) - 动态发表时间
                + text: `霹雳哗啦动态内容` (string,required) - 动态内容
                + pics(array[object],fixed) - 动态相关图片数组
                    + (object)
                        + name: `xxx`(string,required) - 动态相关图片名字1
                        + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                        + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                        + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                        + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + retweeted(object,required) - 转发动态信息obj
                    + id: `1112212`(string,required) - 转发动态的id
                    + text: `霹雳哗啦转发动态的内容`(string,required) - 转发动态的内容
                    + created_at: `10月29日 15:10`(string,required) - 转发动态创建的时间
                    + user(object,required) - 转发动态发表人信息对象
                        + id: `1111222` (string,required) - 转发动态发表人id
                        + name: `王小三` (string,required) - 转发动态发表人name
                        + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 转发动态发表人头像地址
                    + pics(array[object],fixed) - 动态相关图片数组
                        + (object)
                            + name: `xxx`(string,required) - 动态相关图片名字1
                            + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                            + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                            + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                            + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + likes(object,required) - 动态点赞信息obj
                    + total_count: 22 (number,required) - 动态点赞人的总数
                    + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                        + Members
                            + 1(number,required)
                            + 0(number,required)
                    + data(array[object],fixed) - 点赞人信息obj
                        + (object)
                            + id: `111222333`(string,required) - 点赞人id
                            + name: `李小龙`(string,required) - 点赞人姓名
                + attach(array[object], fixed) - 动态附件(出了图片和视频的附件类型)
                    + (object)
                        + id: `123123` - 附件id
                        + name: `附件名称` - 附件名称
                        + download_url: `http://iflytek.lezhiyun.cn/jssq/resource/3613/download` - 下载地址
                        + type: `doc` - 附件类型(不是图片和视频)
                + vedio(array[object], fixed) - 视频
                    + (object)
                        + id: `221234` - 视频资源id
                        + name: `魔兽预告片` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 1(number)
                                + 0(number)
                        + url: `http://v.youku.com/v_show/id_XMTU5NzgzNzA3Ng==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0`
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://covteam.u.qiniudn.com/oceans.mp4` - 视频浏览链接
                        + cover: `http://covteam.u.qiniudn.com/poster.png` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的2` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://7xqjp2.com1.z0.glb.clouddn.com/5089.mp4` - 视频浏览链接
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片

## 获取指定动态ID的详情 [GET /feeds/{id}]

这是个人页面的接口，获取动态评论的时候需要返回图片信息

+ Parameters
    + id: `123123` (string,optional) - 动态id

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + comments(object,required) - 所有动态评论数组
            + total_count: 100 (number,required) - 所有动态评论总数
            + data (array[object],fixed) - 所有动态评论
                + (object)
                    + id: `9890`(string,required) - 评论id
                    + user(object,required) - 评论人的信息obj
                        + id: `231123`(string,required) - 评论人的id
                        + name: `周润发`(string,required) - 评论人的name
                        + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                    + reply(object,required) - 评论回复人信息obj
                        + id: `765665`(string,required) - 评论回复人的id
                        + name: `赌神`(string,required) - 评论回复人的名字
                    + created_at: `12秒前`(string,required) - 评论时间
                    + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                    + pics(array[object],fixed) - 评论图片或回复图片数组
                        + (object)
                            + name: `xxx`(string,required) - 评论图片或回复图片名字1
                            + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                            + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                            + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                            + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
        + user(object,required) - 动态发表人信息对象
            + id: `1111` (string,required) - 动态发表人id
            + name: `王小二` (string,required) - 动态发表人name
            + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
        + created_at: `10月18日 20:14` (string,required) - 动态发表时间
        + text: `霹雳哗啦动态内容` (string,required) - 动态内容
        + pics(array[object],fixed) - 动态相关图片数组
            + (object)
                + name: `xxx`(string,required) - 动态相关图片名字1
                + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
        + retweeted(object,required) - 转发动态信息obj
            + id: `1112212`(string,required) - 转发动态的id
            + text: `霹雳哗啦转发动态的内容`(string,required) - 转发动态的内容
            + created_at: `10月29日 15:10`(string,required) - 转发动态创建的时间
            + user(object,required) - 转发动态发表人信息对象
                + id: `1111222` (string,required) - 转发动态发表人id
                + name: `王小三` (string,required) - 转发动态发表人name
                + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 转发动态发表人头像地址
            + pics(array[object],fixed) - 动态相关图片数组
                + (object)
                    + name: `xxx`(string,required) - 动态相关图片名字1
                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
        + likes(object,required) - 动态点赞信息obj
            + total_count: 22 (number,required) - 动态点赞人的总数
            + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                + Members
                    + 1(number,required)
                    + 0(number,required)
            + data(array[object],fixed) - 点赞人信息obj
                + (object)
                    + id: `111222333`(string,required) - 点赞人id
                    + name: `李小龙`(string,required) - 点赞人姓名
        + attach(array[object], fixed) - 动态附件(出了图片和视频的附件类型)
            + (object)
                + id: `123123` - 附件id
                + name: `附件名称` - 附件名称
                + download_url: `http://iflytek.lezhiyun.cn/jssq/resource/3613/download` - 下载地址
                + type: `doc` - 附件类型(不是图片和视频)
        + vedio(array[object], fixed) - 视频
            + (object)
                + id: `221234` - 视频资源id
                + name: `魔兽预告片` - 视频资源名称
                + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                    + Members
                        + 1(number)
                        + 0(number)
                + url: `http://v.youku.com/v_show/id_XMTU5NzgzNzA3Ng==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0`
                + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
            + (object)
                + id: `111221234` - 视频资源id
                + name: `本地的` - 视频资源名称
                + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                    + Members
                        + 0(number)
                        + 1(number)
                + url: `http://covteam.u.qiniudn.com/oceans.mp4` - 视频浏览链接
                + cover: `http://covteam.u.qiniudn.com/poster.png` - 封面图片
            + (object)
                + id: `111221234` - 视频资源id
                + name: `本地的2` - 视频资源名称
                + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                    + Members
                        + 0(number)
                        + 1(number)
                + url: `http://7xqjp2.com1.z0.glb.clouddn.com/5089.mp4` - 视频浏览链接
                + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片

## 获取指定动态的评论 [GET /feed/{id}/comments]

GET /feeds/{id}/comments -- 这里不能有相同的接口名称，找到问题在解决(和原来一样只是加了获取评论的图片，其他没变)
看之前的api文档是返回对象包括总数和数据，但看线上请求是直接返回了数据数组，先按照线上的返回数据数组，有问题再改

+ Parameters
    + id: `1231231`(string,required) - 动态id

+ Response 200 (application/json;charset=utf-8)
    + Attributes (array[object],fixed)
        + (object)
            + id: `9890`(string,required) - 评论id
            + user(object,required) - 评论人的信息obj
                + id: `231123`(string,required) - 评论人的id
                + name: `周润发`(string,required) - 评论人的name
                + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
            + reply(object,required) - 评论回复人信息obj
                + id: `765665`(string,required) - 评论回复人的id
                + name: `赌神`(string,required) - 评论回复人的名字
            + created_at: `12秒前`(string,required) - 评论时间
            + text: `霹雳哗啦评论的内容评论成功返回的评论哈`(string,required) - 评论的内容
            + pics(array[object],fixed) - 评论图片或回复图片数组
                + (object)
                    + name: `xxx`(string,required) - 评论图片或回复图片名字1
                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)



## 发表动态/话题 [POST /feeds]

ps: 之前的接口是发表个人动态,和现在的发表群组动态合并,如果有forumId这个字段就是发表群组动态，没有就是个人动态
ps: 发表群动态和发表群话题使用这同一个接口，只不过发表话题的时候text 需要在两边加'#',例如: #这是话题的内容#,注意需要forumId

1:发表个人动态就是之前的接口
2:发表指定的群状态就带forumId字段  是群组的id
3:发表指定群话题就是带forumId字段  是群组的id，text是前后带#     ——>   #话题内容#
4:在指定的话题下发言: 带forumId字段  是话题的id   ，text是前后不带#



+ Request (application/json;charset=utf-8)
    + Attributes
        + forumId: `231231`(string,required) - 在群组在发状态就是群组id,在某个话题下发言就是话题的id
        + text: `发表动态内容啊啊啊`(string,required) - 动态内容
        + postFile: `123123:xxx.png|234242:yyy.jpg|`(string,required) - 上传图片(前台需要拼接)
        + isMyFeeds(enum,required) - 是否同时发送到个人动态(1:是,2:否)
            + Members
                + 1(number)
                + 2(number)
        + permission(enum,required) - 动态可见状态(-1: 公开 0: 粉丝可见 1: 群组可见 2: 仅自己可见)
            + Members
                + 1(number)
                + 2(number)
                + 0(number)
                + `-1`(string)
+ Response 201 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 操作是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息
