FORMAT: 1.0.1

# 教研社区 API 文档


## 注意事项


:::warning
API 前缀为 `/jssq/api` 版本为 `1.0` ，在 url 地址上加参数 `&version=1.0`
:::

所有的 API 请求都是通过 json web token 进行获取，在 请求header 头里带上，如下。

```
Authorization: Bearer 5262d64b892e8d4341000001
```
后端应首先验证 token 信息是否准确，错误应该返回 401 Unauthorized。

严格的以 HTTP 请求状态码表示请求是否成功。如下：

- GET 请求成功 200 OK
- POST 请求成功 201 Created,
  一般情况下,所有的POST请求返回的内容都是新建资源的id,如果还需要获取其他内容,会在api中写出。
- PUT 请求成功
  - 创建资源返回 201 Created
  - 更新资源返回 200 OK
- DELETE 请求成功返回 204 No Content


所有错误除了 404 应该返回具体的错误信息，如：

```js
{
  "message": "Permission denied"
}
```

- 服务器找不到资源：404 Not Found
- 验证身份，token 错误: 401 Unauthorized
- 身份验证成功但仍然不允许客户端访问资源(没有权限)：403 Forbidden
- 请求格式正确，但由于含有语义错误，无法响应: 422 Unprocessable Entity
  并且应该返回错误信息 errors:
  例如：

  ```js
    {
      "message": "Validation Failed",
      "errors": [
        {
          "resource": "Issue",
          "field": "title",
          "code": "required"
        }
      ]
    }
  ```
  其中 errors 各字段表示：
  - resource 表示资源，
  - field 表示key
  - code 表示错误类型：
    - invalid：某个字段的值非法，接口文档中会提供响应的信息，
    - required： 缺失某个必须的字段，
    - not_exist: 说明某个字段的值代表的资源不存在
    - already_exist: 说明某个字段的值已经存在


返回的 json 数据 应该严格的按照数据格式返回，为空时也应该返回响应的数据类型为空的值，如：

- `object` 空应该返回 `null` 且不是字符串 `"null"`
- `array` 空应该返回 `[]`
- `string` 空应该返回 `''`

所有时间都是以时间戳的形式进行传输,如:

- created_at: 1466990064 创建时间,格式为Number(10位)。

注意 为了规范:

:::warning
1. 所有 URL 地址上的单词若需要分割均用下划线显示, 如 per_page
2.  所有 Response 回来的 JSON 中的key 一律用驼峰发命名，不得用下划线显示
:::
# Group API 修改记录

在这里写每次API修改的内容。
## 2016年10月25日
1.新增三个接口(新建学科群需要填写类型，学段，学科)<br />
    - <a href="#群组设置-获取新建学科群是选择群类型-get">获取新建学科群是选择群类型</a><br />
    - <a href="#群组设置-获取新建学科群是选择群学段-get">获取新建学科群是选择群学段</a><br />
    - <a href="#群组设置-获取新建学科群是选择群学科-get">获取新建学科群是选择群学科</a>

## 2016年10月27日
1.漏了修改三个老接口(获取动态，获取动态详情，获取指定动态的评论，需要返回相关平路你的图片)<br />
    - <a href="#修改之前的接口-获取全部动态-get">获取全部动态</a><br />
    - <a href="#修改之前的接口-获取指定动态id的详情-get">获取指定动态id的详情</a><br />
    - <a href="#群组设置-获取指定动态的评论-get">获取指定动态的评论</a>

## 2016年10月31日
1.新增两个接口(资源点赞和删除)<br />
    - <a href="#群组资源-点赞某个资源-post">点赞某个资源</a><br />
    - <a href="#群组资源-删除某个资源-delete">删除某个资源</a><br />
2.修改创建群组接口,区管理员创建一个群的时候和指定群主和群管理员,删除获取群类型的接口(可写死)<br />
    - <a href="#群组设置-新建群-post">新建群</a><br />

## 2016年11月01日
1.修改接口，返回用户信息，添加返回学校id<br />
    - <a href="#修改之前的接口-返回当前用户信息-get">返回当前用户信息</a><br />
2.新增接口，上传群组头像<br/>
    - <a href="#群组设置-上传群头像-post">上传群头像</a><br />
3.合并设置管理员和取消管理员接口
    - <a href="#群组成员-移除管理员-添加管理员-post">设置管理员</a><br />
## 2016年11月02日
1.修改接口，返回群组基本信息,判断角色<br />
    - <a href="#群组设置-获取群组基本信息-get">获取群组基本信息</a><br />
## 2016年11月03日
1.修改接口，发表动态,和发表话题，发表群组动态，发表话题发言统一使用<br />
    - <a href="#修改之前的接口-发表动态-话题-post">发表动态-话题</a><br />
2.所有有关权限操作都使用role(1:群主,2:管理员,3:普通成员,4:不是本群成员)<br />

## 2016年12月12日
1.修改接口，获取动态和动态详情，添加附件下载功能和视频播放功能<br />
2.群组资源增加视频播放功能<br />
3.获取群组基本信息添加群组背景图片字段
# Group 修改之前的接口

## 返回当前用户信息 [GET /who]
这个接口之前就有，现在修改，返回此用户的角色(系统管理员，校管理员，普通成员)

+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + id: `12312312`(string,required) - 当前用户的id
        + username: `zhourunfa`(string,required) - 当前用户登录的用户名
        + name: `周润发`(string,required) - 当前用户的名字
        + school: `乐知行学校`(string,required) - 当前用户所在学校
        + school_id: `31231`(string,required) - 当前用户所在学校id
        + profile_image_url: `http:www.baidu.com/xxx.jpg`(string,required) - 当前用户头像
        + type(enum,required) - 用户角色判断(1:系统管理员,2:区管理员,3:校管理员,4:普通教师)
            + Members
                + 1(number,required)
                + 2(number,required)
                + 3(number,required)
                + 4(number,required)

## 发表评论 [POST /feeds/{id}/comments]

修改之前的接口，需要评论可以带图片

+ Parameters
    + id: `112121212`(string,required) - 群组的id

+ Request (application/json;charset=utf-8)
    + Attributes
        + postFile: `12312312:xxx.png|`(string,required) - 评论动态时上传的图片(评论只能一张图片)
        + replyId: `131231`(string,required) - 回复的id,如果没有代表直接回复该条动态
        + text: `霹雳哗啦评论内容啊啊啊啊`(string,required) - 评论的内容

+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 移除是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息


## 获取全部动态 [GET /feeds{?page,per_page}]

这是个人页面的接口，获取动态评论的时候需要返回图片信息,
2016年12月06日, 再次修改, 增加视频在线播放功能

+ Parameters
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + total_count: 100 (number,required) - 数据总数
        + data(array[object], fixed) - 所有动态
            + (object)
                + id: `123456` (string,required) - 动态id
                + comments(object,required) - 动态评论数组(目前在首页只显示三条，详情中全部显示)
                    + total_count: 100 (number,required) - 所有动态评论总数
                    + data (array[object],fixed) - 动态评论的前三条
                        + (object)
                            + id: `9890`(string,required) - 评论id
                            + user(object,required) - 评论人的信息obj
                                + id: `231123`(string,required) - 评论人的id
                                + name: `周润发`(string,required) - 评论人的name
                                + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                            + reply(object,required) - 评论回复人信息obj
                                + id: `765665`(string,required) - 评论回复人的id
                                + name: `赌神`(string,required) - 评论回复人的名字
                            + created_at: `12秒前`(string,required) - 评论时间
                            + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                            + pics(array[object],fixed) - 评论图片或回复图片数组
                                + (object)
                                    + name: `xxx`(string,required) - 评论图片或回复图片名字1
                                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + user(object,required) - 动态发表人信息对象
                    + id: `1111` (string,required) - 动态发表人id
                    + name: `王小二` (string,required) - 动态发表人name
                    + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
                + created_at: `10月18日 20:14` (string,required) - 动态发表时间
                + text: `霹雳哗啦动态内容` (string,required) - 动态内容
                + pics(array[object],fixed) - 动态相关图片数组
                    + (object)
                        + name: `xxx`(string,required) - 动态相关图片名字1
                        + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                        + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                        + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                        + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + retweeted(object,required) - 转发动态信息obj
                    + id: `1112212`(string,required) - 转发动态的id
                    + text: `霹雳哗啦转发动态的内容`(string,required) - 转发动态的内容
                    + created_at: `10月29日 15:10`(string,required) - 转发动态创建的时间
                    + user(object,required) - 转发动态发表人信息对象
                        + id: `1111222` (string,required) - 转发动态发表人id
                        + name: `王小三` (string,required) - 转发动态发表人name
                        + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 转发动态发表人头像地址
                    + pics(array[object],fixed) - 动态相关图片数组
                        + (object)
                            + name: `xxx`(string,required) - 动态相关图片名字1
                            + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                            + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                            + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                            + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + likes(object,required) - 动态点赞信息obj
                    + total_count: 22 (number,required) - 动态点赞人的总数
                    + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                        + Members
                            + 1(number,required)
                            + 0(number,required)
                    + data(array[object],fixed) - 点赞人信息obj
                        + (object)
                            + id: `111222333`(string,required) - 点赞人id
                            + name: `李小龙`(string,required) - 点赞人姓名
                + attach(array[object], fixed) - 动态附件(出了图片和视频的附件类型)
                    + (object)
                        + id: `123123` - 附件id
                        + name: `附件名称` - 附件名称
                        + download_url: `http://iflytek.lezhiyun.cn/jssq/resource/3613/download` - 下载地址
                        + type: `doc` - 附件类型(不是图片和视频)
                + vedio(array[object], fixed) - 视频
                    + (object)
                        + id: `221234` - 视频资源id
                        + name: `魔兽预告片` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 1(number)
                                + 0(number)
                        + url: `http://v.youku.com/v_show/id_XMTU5NzgzNzA3Ng==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0`
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://covteam.u.qiniudn.com/oceans.mp4` - 视频浏览链接
                        + cover: `http://covteam.u.qiniudn.com/poster.png` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的2` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://7xqjp2.com1.z0.glb.clouddn.com/5089.mp4` - 视频浏览链接
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片

## 获取指定动态ID的详情 [GET /feeds/{id}]

这是个人页面的接口，获取动态评论的时候需要返回图片信息

+ Parameters
    + id: `123123` (string,optional) - 动态id

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + comments(object,required) - 所有动态评论数组
            + total_count: 100 (number,required) - 所有动态评论总数
            + data (array[object],fixed) - 所有动态评论
                + (object)
                    + id: `9890`(string,required) - 评论id
                    + user(object,required) - 评论人的信息obj
                        + id: `231123`(string,required) - 评论人的id
                        + name: `周润发`(string,required) - 评论人的name
                        + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                    + reply(object,required) - 评论回复人信息obj
                        + id: `765665`(string,required) - 评论回复人的id
                        + name: `赌神`(string,required) - 评论回复人的名字
                    + created_at: `12秒前`(string,required) - 评论时间
                    + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                    + pics(array[object],fixed) - 评论图片或回复图片数组
                        + (object)
                            + name: `xxx`(string,required) - 评论图片或回复图片名字1
                            + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                            + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                            + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                            + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
        + user(object,required) - 动态发表人信息对象
            + id: `1111` (string,required) - 动态发表人id
            + name: `王小二` (string,required) - 动态发表人name
            + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
        + created_at: `10月18日 20:14` (string,required) - 动态发表时间
        + text: `霹雳哗啦动态内容` (string,required) - 动态内容
        + pics(array[object],fixed) - 动态相关图片数组
            + (object)
                + name: `xxx`(string,required) - 动态相关图片名字1
                + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
        + retweeted(object,required) - 转发动态信息obj
            + id: `1112212`(string,required) - 转发动态的id
            + text: `霹雳哗啦转发动态的内容`(string,required) - 转发动态的内容
            + created_at: `10月29日 15:10`(string,required) - 转发动态创建的时间
            + user(object,required) - 转发动态发表人信息对象
                + id: `1111222` (string,required) - 转发动态发表人id
                + name: `王小三` (string,required) - 转发动态发表人name
                + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 转发动态发表人头像地址
            + pics(array[object],fixed) - 动态相关图片数组
                + (object)
                    + name: `xxx`(string,required) - 动态相关图片名字1
                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
        + likes(object,required) - 动态点赞信息obj
            + total_count: 22 (number,required) - 动态点赞人的总数
            + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                + Members
                    + 1(number,required)
                    + 0(number,required)
            + data(array[object],fixed) - 点赞人信息obj
                + (object)
                    + id: `111222333`(string,required) - 点赞人id
                    + name: `李小龙`(string,required) - 点赞人姓名
        + attach(array[object], fixed) - 动态附件(出了图片和视频的附件类型)
            + (object)
                + id: `123123` - 附件id
                + name: `附件名称` - 附件名称
                + download_url: `http://iflytek.lezhiyun.cn/jssq/resource/3613/download` - 下载地址
                + type: `doc` - 附件类型(不是图片和视频)
        + vedio(array[object], fixed) - 视频
            + (object)
                + id: `221234` - 视频资源id
                + name: `魔兽预告片` - 视频资源名称
                + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                    + Members
                        + 1(number)
                        + 0(number)
                + url: `http://v.youku.com/v_show/id_XMTU5NzgzNzA3Ng==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0`
                + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
            + (object)
                + id: `111221234` - 视频资源id
                + name: `本地的` - 视频资源名称
                + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                    + Members
                        + 0(number)
                        + 1(number)
                + url: `http://covteam.u.qiniudn.com/oceans.mp4` - 视频浏览链接
                + cover: `http://covteam.u.qiniudn.com/poster.png` - 封面图片
            + (object)
                + id: `111221234` - 视频资源id
                + name: `本地的2` - 视频资源名称
                + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                    + Members
                        + 0(number)
                        + 1(number)
                + url: `http://7xqjp2.com1.z0.glb.clouddn.com/5089.mp4` - 视频浏览链接
                + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片

## 获取指定动态的评论 [GET /feed/{id}/comments]

GET /feeds/{id}/comments -- 这里不能有相同的接口名称，找到问题在解决(和原来一样只是加了获取评论的图片，其他没变)
看之前的api文档是返回对象包括总数和数据，但看线上请求是直接返回了数据数组，先按照线上的返回数据数组，有问题再改

+ Parameters
    + id: `1231231`(string,required) - 动态id

+ Response 200 (application/json;charset=utf-8)
    + Attributes (array[object],fixed)
        + (object)
            + id: `9890`(string,required) - 评论id
            + user(object,required) - 评论人的信息obj
                + id: `231123`(string,required) - 评论人的id
                + name: `周润发`(string,required) - 评论人的name
                + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
            + reply(object,required) - 评论回复人信息obj
                + id: `765665`(string,required) - 评论回复人的id
                + name: `赌神`(string,required) - 评论回复人的名字
            + created_at: `12秒前`(string,required) - 评论时间
            + text: `霹雳哗啦评论的内容评论成功返回的评论哈`(string,required) - 评论的内容
            + pics(array[object],fixed) - 评论图片或回复图片数组
                + (object)
                    + name: `xxx`(string,required) - 评论图片或回复图片名字1
                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)



## 发表动态/话题 [POST /feeds]

ps: 之前的接口是发表个人动态,和现在的发表群组动态合并,如果有forumId这个字段就是发表群组动态，没有就是个人动态
ps: 发表群动态和发表群话题使用这同一个接口，只不过发表话题的时候text 需要在两边加'#',例如: #这是话题的内容#,注意需要forumId

1:发表个人动态就是之前的接口
2:发表指定的群状态就带forumId字段  是群组的id
3:发表指定群话题就是带forumId字段  是群组的id，text是前后带#     ——>   #话题内容#
4:在指定的话题下发言: 带forumId字段  是话题的id   ，text是前后不带#



+ Request (application/json;charset=utf-8)
    + Attributes
        + forumId: `231231`(string,required) - 在群组在发状态就是群组id,在某个话题下发言就是话题的id
        + text: `发表动态内容啊啊啊`(string,required) - 动态内容
        + postFile: `123123:xxx.png|234242:yyy.jpg|`(string,required) - 上传图片(前台需要拼接)
        + isMyFeeds(enum,required) - 是否同时发送到个人动态(1:是,2:否)
            + Members
                + 1(number)
                + 2(number)
        + permission(enum,required) - 动态可见状态(-1: 公开 0: 粉丝可见 1: 群组可见 2: 仅自己可见)
            + Members
                + 1(number)
                + 2(number)
                + 0(number)
                + `-1`(string)
+ Response 201 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 操作是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息
# Group 群组列表动态

## 获取我的群 [GET /my_group{?page,per_page}]

包括我创建的，我管理的，我加入的

+ Parameters
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + total_count: 100 (number,required) - 数据总数
        + data(array[object], fixed) - 所有群组
            + (object)
                + id: `1231231` (string,required) - 群组id
                + name: `乐知行测试群` (string,required) - 群组名字
                + created_at: `10月18日 17:56` - 该群组创建的时间
                + member: 100(number,required) - 成员人数
                + cover_image_url: `http:www.baidu.com/xxx.jpg` - 该群组头像图片
            + (object)
                + id: `1231232` (string,required) - 群组id
                + name: `前端学习群` (string,required) - 群组名字
                + created_at: `10月18日 17:56` - 该群组创建的时间
                + member: 100(number,required) - 成员人数
                + cover_image_url: `http:www.baidu.com/xxx.jpg` - 该群组头像图片


## 获取所有与自己相关群的动态 [GET /all_group_feeds{?page,per_page}]

与自己相关群：我创建的，我管理的，我加入的

+ Parameters
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + total_count: 100 (number,required) - 数据总数
        + data(array[object], fixed) - 所有动态
            + (object)
                + id: `123456` (string,required) - 动态id
                + role(enum,required) - 当前用户在动态所在群的角色(1:群主,2:管理员,3:普通成员,4:不是本群成员)
                    + Members
                        + 1(number,required)
                        + 2(number,required)
                        + 3(number,required)
                        + 4(number,required)
                + group: `小学语文学科群` (string,required) - 动态发表所在群
                + comments(object,required) - 动态评论数组(目前在首页只显示三条，详情中全部显示)
                    + total_count: 100 (number,required) - 所有动态评论总数
                    + data (array[object],fixed) - 动态评论的前三条
                        + (object)
                            + id: `9890`(string,required) - 评论id
                            + user(object,required) - 评论人的信息obj
                                + id: `231123`(string,required) - 评论人的id
                                + name: `周润发`(string,required) - 评论人的name
                                + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                            + reply(object,required) - 评论回复人信息obj
                                + id: `765665`(string,required) - 评论回复人的id
                                + name: `赌神`(string,required) - 评论回复人的名字
                            + created_at: `12秒前`(string,required) - 评论时间
                            + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                            + pics(array[object],fixed) - 评论图片或回复图片数组
                                + (object)
                                    + name: `xxx`(string,required) - 评论图片或回复图片名字1
                                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + user(object,required) - 动态发表人信息对象
                    + id: `1111` (string,required) - 动态发表人id
                    + name: `王小二` (string,required) - 动态发表人name
                    + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
                + created_at: `10月18日 20:14` (string,required) - 动态发表时间
                + text: `霹雳哗啦动态内容` (string,required) - 动态内容
                + pics(array[object],fixed) - 动态相关图片数组
                    + (object)
                        + name: `xxx`(string,required) - 动态相关图片名字1
                        + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                        + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                        + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                        + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + retweeted(object,required) - 转发动态信息obj
                    + id: `1112212`(string,required) - 转发动态的id
                    + text: `霹雳哗啦转发动态的内容`(string,required) - 转发动态的内容
                    + created_at: `10月29日 15:10`(string,required) - 转发动态创建的时间
                    + user(object,required) - 转发动态发表人信息对象
                        + id: `1111222` (string,required) - 转发动态发表人id
                        + name: `王小三` (string,required) - 转发动态发表人name
                        + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 转发动态发表人头像地址
                    + pics(array[object],fixed) - 转发动态相关图片数组
                        + (object)
                            + name: `xxx`(string,required) - 转发动态相关图片名字1
                            + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 转发动态相关图片缩略图地址
                            + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 转发动态相关图片原图地址
                            + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                            + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + likes(object,required) - 动态点赞信息obj
                    + total_count: 22 (number,required) - 动态点赞人的总数
                    + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                        + Members
                            + 1(number,required)
                            + 0(number,required)
                    + data(array[object],fixed) - 点赞人信息obj
                        + (object)
                            + id: `111222333`(string,required) - 点赞人id
                            + name: `李小龙`(string,required) - 点赞人姓名
                + attach(array[object], fixed) - 动态附件(出了图片和视频的附件类型)
                    + (object)
                        + id: `123123` - 附件id
                        + name: `附件名称` - 附件名称
                        + download_url: `http://iflytek.lezhiyun.cn/jssq/resource/3613/download` - 下载地址
                        + type: `doc` - 附件类型(不是图片和视频)
                + vedio(array[object], fixed) - 视频
                    + (object)
                        + id: `221234` - 视频资源id
                        + name: `魔兽预告片` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 1(number)
                                + 0(number)
                        + url: `http://v.youku.com/v_show/id_XMTU5NzgzNzA3Ng==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0`
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://covteam.u.qiniudn.com/oceans.mp4` - 视频浏览链接
                        + cover: `http://covteam.u.qiniudn.com/poster.png` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的2` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://7xqjp2.com1.z0.glb.clouddn.com/5089.mp4` - 视频浏览链接
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
## 获取指定群动态详情 [GET /group_feeds/{feed_id}]

+ Parameters
    + feed_id: `1231231`(string,required) - 动态id

+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + role(enum,required) - 当前用户在动态所在群的角色(1:群主,2:管理员,3:普通成员,4:不是本群成员)
            + Members
                + 1(number,required)
                + 2(number,required)
                + 3(number,required)
                + 4(number,required)
        + group: `小学语文学科群` (string,required) - 动态发表所在群
        + comments(object,required) - 所有动态评论数组
            + total_count: 100 (number,required) - 所有动态评论总数
            + data (array[object],fixed) - 所有动态评论
                + (object)
                    + id: `9890`(string,required) - 评论id
                    + user(object,required) - 评论人的信息obj
                        + id: `231123`(string,required) - 评论人的id
                        + name: `周润发`(string,required) - 评论人的name
                        + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                    + reply(object,required) - 评论回复人信息obj
                        + id: `765665`(string,required) - 评论回复人的id
                        + name: `赌神`(string,required) - 评论回复人的名字
                    + created_at: `12秒前`(string,required) - 评论时间
                    + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                    + pics(array[object],fixed) - 评论图片或回复图片数组
                        + (object)
                            + name: `xxx`(string,required) - 评论图片或回复图片名字1
                            + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                            + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                            + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                            + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
        + user(object,required) - 动态发表人信息对象
            + id: `1111` (string,required) - 动态发表人id
            + name: `王小二` (string,required) - 动态发表人name
            + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
        + created_at: `10月18日 20:14` (string,required) - 动态发表时间
        + text: `霹雳哗啦动态内容` (string,required) - 动态内容
        + pics(array[object],fixed) - 动态相关图片数组
            + (object)
                + name: `xxx`(string,required) - 动态相关图片名字1
                + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
        + retweeted(object,required) - 转发动态信息obj
            + id: `1112212`(string,required) - 转发动态的id
            + text: `霹雳哗啦转发动态的内容`(string,required) - 转发动态的内容
            + created_at: `10月29日 15:10`(string,required) - 转发动态创建的时间
            + user(object,required) - 转发动态发表人信息对象
                + id: `1111222` (string,required) - 转发动态发表人id
                + name: `王小三` (string,required) - 转发动态发表人name
                + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 转发动态发表人头像地址
            + pics(array[object],fixed) - 动态相关图片数组
                + (object)
                    + name: `xxx`(string,required) - 动态相关图片名字1
                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
        + likes(object,required) - 动态点赞信息obj
            + total_count: 22 (number,required) - 动态点赞人的总数
            + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                + Members
                    + 1(number,required)
                    + 0(number,required)
            + data(array[object],fixed) - 点赞人信息obj
                + (object)
                    + id: `111222333`(string,required) - 点赞人id
                    + name: `李小龙`(string,required) - 点赞人姓名
        + attach(array[object], fixed) - 动态附件(出了图片和视频的附件类型)
            + (object)
                + id: `123123` - 附件id
                + name: `附件名称` - 附件名称
                + download_url: `http://iflytek.lezhiyun.cn/jssq/resource/3613/download` - 下载地址
                + type: `doc` - 附件类型(不是图片和视频)
        + vedio(array[object], fixed) - 视频
            + (object)
                + id: `221234` - 视频资源id
                + name: `魔兽预告片` - 视频资源名称
                + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                    + Members
                        + 1(number)
                        + 0(number)
                + url: `http://v.youku.com/v_show/id_XMTU5NzgzNzA3Ng==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0`
                + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
            + (object)
                + id: `111221234` - 视频资源id
                + name: `本地的` - 视频资源名称
                + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                    + Members
                        + 0(number)
                        + 1(number)
                + url: `http://covteam.u.qiniudn.com/oceans.mp4` - 视频浏览链接
                + cover: `http://covteam.u.qiniudn.com/poster.png` - 封面图片
            + (object)
                + id: `111221234` - 视频资源id
                + name: `本地的2` - 视频资源名称
                + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                    + Members
                        + 0(number)
                        + 1(number)
                + url: `http://7xqjp2.com1.z0.glb.clouddn.com/5089.mp4` - 视频浏览链接
                + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
# Group 群组主页

## 获取指定群的所有动态 [GET /group_feeds{?group_id,page,per_page}]

+ Parameters
    + group_id: `112121212`(string,required) - 指定群组的id
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + total_count: 100 (number,required) - 数据总数
        + data(array[object], fixed) - 所有动态
            + (object)
                + id: `123456` (string,required) - 动态id
                + group: `小学语文学科群` (string,required) - 动态发表所在群
                + comments(object,required) - 动态评论数组(目前在首页只显示三条，详情中全部显示)
                    + total_count: 100 (number,required) - 所有动态评论总数
                    + data (array[object],fixed) - 动态评论的前三条
                        + (object)
                            + id: `9890`(string,required) - 评论id
                            + user(object,required) - 评论人的信息obj
                                + id: `231123`(string,required) - 评论人的id
                                + name: `周润发`(string,required) - 评论人的name
                                + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                            + reply(object,required) - 评论回复人信息obj
                                + id: `765665`(string,required) - 评论回复人的id
                                + name: `赌神`(string,required) - 评论回复人的名字
                            + created_at: `12秒前`(string,required) - 评论时间
                            + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                            + pics(array[object],fixed) - 评论图片或回复图片数组
                                + (object)
                                    + name: `xxx`(string,required) - 评论图片或回复图片名字1
                                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + user(object,required) - 动态发表人信息对象
                    + id: `1111` (string,required) - 动态发表人id
                    + name: `王小二` (string,required) - 动态发表人name
                    + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
                + created_at: `10月18日 20:14` (string,required) - 动态发表时间
                + text: `霹雳哗啦动态内容` (string,required) - 动态内容
                + pics(array[object],fixed) - 动态相关图片数组
                    + (object)
                        + name: `xxx`(string,required) - 动态相关图片名字1
                        + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                        + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                        + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                        + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + retweeted(object,required) - 转发动态信息obj
                    + id: `1112212`(string,required) - 转发动态的id
                    + text: `霹雳哗啦转发动态的内容`(string,required) - 转发动态的内容
                    + created_at: `10月29日 15:10`(string,required) - 转发动态创建的时间
                    + user(object,required) - 转发动态发表人信息对象
                        + id: `1111222` (string,required) - 转发动态发表人id
                        + name: `王小三` (string,required) - 转发动态发表人name
                        + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 转发动态发表人头像地址
                    + pics(array[object],fixed) - 动态相关图片数组
                        + (object)
                            + name: `xxx`(string,required) - 动态相关图片名字1
                            + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                            + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                            + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                            + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + likes(object,required) - 动态点赞信息obj
                    + total_count: 22 (number,required) - 动态点赞人的总数
                    + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                        + Members
                            + 1(number,required)
                            + 0(number,required)
                    + data(array[object],fixed) - 点赞人信息obj
                        + (object)
                            + id: `111222333`(string,required) - 点赞人id
                            + name: `李小龙`(string,required) - 点赞人姓名
                + attach(array[object], fixed) - 动态附件(出了图片和视频的附件类型)
                    + (object)
                        + id: `123123` - 附件id
                        + name: `附件名称` - 附件名称
                        + download_url: `http://iflytek.lezhiyun.cn/jssq/resource/3613/download` - 下载地址
                        + type: `doc` - 附件类型(不是图片和视频)
                + vedio(array[object], fixed) - 视频
                    + (object)
                        + id: `221234` - 视频资源id
                        + name: `魔兽预告片` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 1(number)
                                + 0(number)
                        + url: `http://v.youku.com/v_show/id_XMTU5NzgzNzA3Ng==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0`
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://covteam.u.qiniudn.com/oceans.mp4` - 视频浏览链接
                        + cover: `http://covteam.u.qiniudn.com/poster.png` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的2` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://7xqjp2.com1.z0.glb.clouddn.com/5089.mp4` - 视频浏览链接
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
            + (object)
                + id: `123456` (string,required) - 动态id
                + group: `小学语文学科群2` (string,required) - 动态发表所在群
                + comments(object,required) - 动态评论数组(目前在首页只显示三条，详情中全部显示)
                    + total_count: 100 (number,required) - 所有动态评论总数
                    + data (array[object],fixed) - 动态评论的前三条
                        + (object)
                            + id: `9890`(string,required) - 评论id
                            + user(object,required) - 评论人的信息obj
                                + id: `231123`(string,required) - 评论人的id
                                + name: `周润发`(string,required) - 评论人的name
                                + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                            + reply(object,required) - 评论回复人信息obj
                                + id: `765665`(string,required) - 评论回复人的id
                                + name: `赌神`(string,required) - 评论回复人的名字
                            + created_at: `12秒前`(string,required) - 评论时间
                            + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                            + pics(array[object],fixed) - 评论图片或回复图片数组
                                + (object)
                                    + name: `xxx`(string,required) - 评论图片或回复图片名字1
                                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + user(object,required) - 动态发表人信息对象
                    + id: `1111` (string,required) - 动态发表人id
                    + name: `王小二` (string,required) - 动态发表人name
                    + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
                + created_at: `10月18日 20:14` (string,required) - 动态发表时间
                + text: `霹雳哗啦动态内容` (string,required) - 动态内容
                + pics(array[object],fixed) - 动态相关图片数组
                    + (object)
                        + name: `xxx`(string,required) - 动态相关图片名字1
                        + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                        + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                        + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                        + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + retweeted(object,required) - 转发动态信息obj
                    + id: `1112212`(string,required) - 转发动态的id
                    + text: `霹雳哗啦转发动态的内容`(string,required) - 转发动态的内容
                    + created_at: `10月29日 15:10`(string,required) - 转发动态创建的时间
                    + user(object,required) - 转发动态发表人信息对象
                        + id: `1111222` (string,required) - 转发动态发表人id
                        + name: `王小三` (string,required) - 转发动态发表人name
                        + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 转发动态发表人头像地址
                    + pics(array[object],fixed) - 动态相关图片数组
                        + (object)
                            + name: `xxx`(string,required) - 动态相关图片名字1
                            + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                            + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                            + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                            + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + likes(object,required) - 动态点赞信息obj
                    + total_count: 22 (number,required) - 动态点赞人的总数
                    + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                        + Members
                            + 1(number,required)
                            + 0(number,required)
                    + data(array[object],fixed) - 点赞人信息obj
                        + (object)
                            + id: `111222333`(string,required) - 点赞人id
                            + name: `李小龙`(string,required) - 点赞人姓名
                + attach(array[object], fixed) - 动态附件(出了图片和视频的附件类型)
                    + (object)
                        + id: `123123` - 附件id
                        + name: `附件名称` - 附件名称
                        + download_url: `http://iflytek.lezhiyun.cn/jssq/resource/3613/download` - 下载地址
                        + type: `doc` - 附件类型(不是图片和视频)
                + vedio(array[object], fixed) - 视频
                    + (object)
                        + id: `221234` - 视频资源id
                        + name: `魔兽预告片` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 1(number)
                                + 0(number)
                        + url: `http://v.youku.com/v_show/id_XMTU5NzgzNzA3Ng==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0`
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://covteam.u.qiniudn.com/oceans.mp4` - 视频浏览链接
                        + cover: `http://covteam.u.qiniudn.com/poster.png` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的2` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://7xqjp2.com1.z0.glb.clouddn.com/5089.mp4` - 视频浏览链接
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
# Group 群组话题

## 获取指定群的所有话题列表 [GET /group_topic{?group_id,page,per_page}]

+ Parameters
    + group_id: `112121212`(string,required) - 指定群组的id
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + total_count: 100(number,required) - 该群的话题总数
        + data(array[object],fixed) - 话题数据
            + (object)
                + id: `12312312312`(string,required) - 话题的id
                + name: `话题名称霹雳哗啦`(string,required) - 话题的名称
                + speak: 100(string,required) - 该话题发言总数
                + isTop(enum,required) - 是否置顶(1:置顶,2:不置顶)
                    + Members
                        + 1(number,required)
                        + 2(number,required)
                + created_at: `2016-01-01`(string,required) - 该话题的创建时间
                + create: `李小龙`(string,required) - 该话题的发起者

## 获取指定话题下的详情 [GET /group_topic_detail{?topic_id,page,per_page}]
ps: 看pc端的是这样的逻辑:每个话题可以有多个发言，每个发言就是一个动态,当进入话题详情时，需要该话题下的所有发言，也就是该话题下的所有动态
群组话题和发现的话题详情都调用这个接口,发现下的就判断isComment可不可以评论
+ Parameters
    + topic_id: `112121212`(string,required) - 指定话题的id
    + page: 1(number,required) - 请求第几页
    + per_page: 10(number,required) - 请求每页的数据量

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + name: `话题名称霹雳哗啦`(string,required) - 话题的名称
        + role(enum,required) - 当前用户在动态所在群的角色(1:群主,2:管理员,3:普通成员,4:不是本群成员)
            + Members
                + 1(number,required)
                + 2(number,required)
                + 3(number,required)
                + 4(number,required)
        + create: `李老师`(string,required) - 话题发起人
        + created_at: `10月19日 16:33`(string,required) - 话题发起时间
        + total_count: 100(number,required) - 该话题发起的所有发言总数
        + data(array[object],fixed) - 该话题的所有发言的数据(和获取动态一样????)
            + (object)
                + id: `123456` (string,required) - 动态id
                + group: `小学语文学科群` (string,required) - 动态发表所在群(原型张没有说用的。带上以防万一)
                + comments(object,required) - 动态评论数组(目前在首页只显示三条，详情中全部显示)
                    + total_count: 100 (number,required) - 所有动态评论总数
                    + data (array[object],fixed) - 动态评论的前三条
                        + (object)
                            + id: `9890`(string,required) - 评论id
                            + user(object,required) - 评论人的信息obj
                                + id: `231123`(string,required) - 评论人的id
                                + name: `周润发`(string,required) - 评论人的name
                                + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                            + reply(object,required) - 评论回复人信息obj
                                + id: `765665`(string,required) - 评论回复人的id
                                + name: `赌神`(string,required) - 评论回复人的名字
                            + created_at: `12秒前`(string,required) - 评论时间
                            + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                + user(object,required) - 动态发表人信息对象
                    + id: `1111` (string,required) - 动态发表人id
                    + name: `王小二` (string,required) - 动态发表人name
                    + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
                + created_at: `10月18日 20:14` (string,required) - 动态发表时间
                + text: `霹雳哗啦动态内容` (string,required) - 动态内容
                + pics(array[object],fixed) - 动态相关图片数组
                    + (object)
                        + name: `xxx`(string,required) - 动态相关图片名字1
                        + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                        + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                        + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                        + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + likes(object,required) - 动态点赞信息obj
                    + total_count: 22 (number,required) - 动态点赞人的总数
                    + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                        + Members
                            + 1(number,required)
                            + 0(number,required)
                    + data(array[object],fixed) - 点赞人信息obj
                        + (object)
                            + id: `111222333`(string,required) - 点赞人id
                            + name: `李小龙`(string,required) - 点赞人姓名
                + attach(array[object], fixed) - 动态附件(出了图片和视频的附件类型)
                    + (object)
                        + id: `123123` - 附件id
                        + name: `附件名称` - 附件名称
                        + download_url: `http://iflytek.lezhiyun.cn/jssq/resource/3613/download` - 下载地址
                        + type: `doc` - 附件类型(不是图片和视频)
                + vedio(array[object], fixed) - 视频
                    + (object)
                        + id: `221234` - 视频资源id
                        + name: `魔兽预告片` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 1(number)
                                + 0(number)
                        + url: `http://v.youku.com/v_show/id_XMTU5NzgzNzA3Ng==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0`
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://covteam.u.qiniudn.com/oceans.mp4` - 视频浏览链接
                        + cover: `http://covteam.u.qiniudn.com/poster.png` - 封面图片
                    + (object)
                        + id: `111221234` - 视频资源id
                        + name: `本地的2` - 视频资源名称
                        + isLine(enum,required) - 是线上的视频还是本地上传的,1: 是线上, 0: 是本地
                            + Members
                                + 0(number)
                                + 1(number)
                        + url: `http://7xqjp2.com1.z0.glb.clouddn.com/5089.mp4` - 视频浏览链接
                        + cover: `http://iflytek.lezhiyun.cn/vfs/js_file/24/7d/72/transpic/24c49d88ac50c2c7d46f044716eafc72.jpg` - 封面图片

## 置顶/取消置顶一个话题 [POST /group_topic_top/{topic_id}]

+ Parameters
    + topic_id: `112121212`(string,required) - 话题id

+ Request (application/json;charset=utf-8)
    + Attributes
        + action(enum,required) - 区别是用来置顶还是取消置顶(1:置顶,0:取消置顶)
            + Members
                + 1(number,required)
                + 2(number,required)

+ Response 201 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 移除是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `操作成功`(string,required) - 操作返回信息


## 删除一个话题 [DELETE /group_topic/{topic_id}]

+ Parameters
    + topic_id: `112121212`(string,required) - 话题id

+ Response 204 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 移除是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息
# Group 群组资源

## 获取指定群的所有资源列表 [GET /group_resouse{?group_id,page,per_page}]

+ Parameters
    + group_id: `112121212`(string,required) - 指定群组的id
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + total_count: 100(number,required) - 该群组的资源总数
        + data(array[object],fixed) - 资源数据
            + (object)
                + status(enum,required) - 资源大类型判断(1: 是视频, 0: 不是视频)
                    + Members
                        + 0(number)
                        + 1(number)
                + id: `12313123`(string,required) - 该资源的id
                + name: `学科建设PPT`(string,required) - 资源的名字
                + download: 1212(number,required) - 下载量
                + download_url: `http://www.baidu.com/xxx.png`(string,required) - 资源下载绝对地址
                + isLove(enum,required) - 该资源当前用户是否已经点赞(1:点过了,2:没有点呢)
                + type: `png`(string,required) - 该资源的类型(例如:png、jpg、doc....)
            + (object)
                + status(enum,required) - 资源大类型判断(1: 是视频, 0: 不是视频)
                    + Members
                        + 1(number)
                        + 0(number)
                + id: `12313124`(string,required) - 该资源的id
                + name: `学科建设PPT`(string,required) - 资源的名字
                + download: 1212(number,required) - 下载量
                + download_url: `http://covteam.u.qiniudn.com/oceans.mp4`(string,required) - 资源下载绝对地址
                + isLove(enum,required) - 该资源当前用户是否已经点赞(1:点过了,2:没有点呢)
                + type: `mp4`(string,required) - 该资源的类型(例如:png、jpg、doc....)


## 删除某个资源 [DELETE /group_resouse/{resource_id}]

+ Parameters
    + resource_id: `112121212`(string,required) - 资源的id

+ Response 204 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 移除是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息
# Group 群组成员

## 获取指定群的所有成员 [GET /group_member{?group_id}]

+ Parameters
    + group_id: `112121212`(string,required) - 指定群组的id

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + leader(object,required) - 群主信息obj
            + id: `12311`(string,required) - 群主id
            + name: `成龙`(string,required) - 群主名字
            + isFollow(enum,required) - 是否已经关注(1:关注了，2:没有关注)
                + Members
                    + 1(number,required)
                    + 2(number,required)
        + admin(array[object],fixed) - 群管理员
            + (object)
                + id: `123111`(string,required) - 群管理员id1
                + name: `成龙`(string,required) - 群管理员名字1
                + isFollow(enum,required) - 是否已经关注
                    + Members
                        + 1(number,required)
                        + 2(number,required)
            + (object)
                + id: `123112`(string,required) - 群管理员id2
                + name: `陈真`(string,required) - 群管理员名字2
                + isFollow(enum,required) - 是否已经关注
                    + Members
                        + 1(number,required)
                        + 2(number,required)
        + member(array[object],fixed) - 群成员
            + (object)
                + id: `124111`(string,required) - 群成员id1
                + name: `霍元甲`(string,required) - 群成员名字1
                + isFollow(enum,required) - 是否已经关注
                    + Members
                        + 1(number,required)
                        + 2(number,required)
            + (object)
                + id: `124112`(string,required) - 群成员id2
                + name: `孙悟空`(string,required) - 群成员名字2
                + isFollow(enum,required) - 是否已经关注
                    + Members
                        + 1(number,required)
                        + 2(number,required)
            + (object)
                + id: `124113`(string,required) - 群成员id3
                + name: `李连杰`(string,required) - 群成员名字3
                + isFollow(enum,required) - 是否已经关注
                    + Members
                        + 1(number,required)
                        + 2(number,required)

## 移除管理员/添加管理员 [POST /group_type]

+ Request (application/json;charset=utf-8)
    + Attributes
        + group_id: `112121212`(string,required) - 群组的id
        + user_id: `11212121111`(string,required) - 群组的id
        + type(enum,required) - 设置的角色(1：管理员，0：普通成员)
            + Members
                + 1(number,required)
                + 0(number,required)
+ Response 201 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 移除是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `移除成功`(string,required) - 操作返回信息
# Group 群组设置

## 获取新建学科群是选择群学段 [GET /group_level]

+ Response 200 (application/json;charset=utf-8)

    + Attributes (array[object], fixed)
        + (object)
            + id: `123` (string,required) - 学段id
            + name: `小学` (string,required) - 学段名字
        + (object)
            + id: `124` (string,required) - 学段id
            + name: `中学` (string,required) - 学段名字

## 获取新建学科群是选择群学科 [GET /group_subject]

+ Response 200 (application/json;charset=utf-8)

    + Attributes (array[object], fixed)
        + (object)
            + id: `123` (string,required) - 类科id
            + name: `自然科学` (string,required) - 类科名字
        + (object)
            + id: `124` (string,required) - 类科id
            + name: `语文` (string,required) - 类科名字

## 新建群 [POST /group]

如果是新建的学科群，才会有type、grade、subject三个字段,这个请求用一个参数传过去result,是将一个对象转为字符串传给后台，需要后台处理
group_create?result=对象转的字符串(所有数据)

+ Request (application/json;charset=utf-8)
    + Attributes
        + new_gropu_type(enum,required) - 新建群组时选择的群组的类型(subject: 学科群,ordinary: 普通群)
            + Members
                + `subject`(string,required)
                + `ordinary`(string,required)
        + cover_image: `12312312:xxx.png`(string,required) - 新建群组上传的头像信息
        + name: `乐知行新建群组`(string,required) - 群组的名称
        + description: `新建群组时的简介啊啊啊啊啊啊啊啊`(string,required) - 群组简介
        + type: `-1` - 群类型(学科群特有字段)(区级传-1,校级传当前用户所在学校,前台写死)
        + level: `222` - 学段id(学科群特有字段)
        + subject: `111` - 学科id(学科群特有字段)
        + member: `[{name:xxx,id:123123,type:member}]`(string,required) - 选择的群成员(是一个数组需要后端处理,如果是选择的整个部门则传部门id，后台需要以部门id获取部门所在成员)
        + admin: `[{name:xxx,id:123123,type:member}]`(string,required) - 选择的群成员(是一个数组需要后端处理,如果是选择的整个部门则传部门id，后台需要以部门id获取部门所在成员)和选择群成员一致
        + leader: `312312312`(string,required) - 选择的群主id(为空或不穿则表示创建者就是群主)

+ Response 201 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 移除是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息


## 修改群组基本信息 [PUT /group_info/{id}]

修改群组基本信息，只允许修改头像，名称，简介(再请求中如果传的为空则代表不修改，使用原来的，那个参数不为空代表只修改那个，其他不变)

+ Parameters
    + id: `112121212`(string,required) - 群组的id

+ Request (application/json;charset=utf-8)
    + Attributes
        + postFile: `12312312:xxx.png`(string,required) - 新建群组上传的头像信息
        + name: `乐知行新建群组`(string,required) - 群组的名称
        + description: `新建群组时的简介啊啊啊啊啊啊啊啊`(string,required) - 群组简介
        + type(object) - 群类型(学科群特有字段)
            + id: `123`(string,required) - 群类型的id
            + name: `区级`(string,required) - 群类型的名称
        + grade(object) - 学段(学科群特有字段)
            + id: `123`(string,required) - 群学段的id
            + name: `小学`(string,required) - 群学段的名称
        + subject(object) - 学科(学科群特有字段)
            + id: `123`(string,required) - 群学科的id
            + name: `自然科学`(string,required) - 群学科的名称
+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 移除是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息

## 获取群组基本信息 [GET /group_info{?group_id,user_id}]

+ Parameters
    + group_id: `112121212`(string,required) - 群组的id
    + user_id: `3123131`(string,required) - 当前用户id(不需要可以忽略)

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + cover_image_url: `http://www.baidu.com/xxx.png`(string,required) - 群头像地址
        + name: `乐知行测试群`(string,required) - 群名称
        + description: `群简介群简介群简介群简介群简介`(string,required) - 群简介
        + type(object) - 群类型(学科群特有字段)
            + id: `123`(string,required) - 群类型的id
            + name: `区级`(string,required) - 群类型的名称
        + grade(object) - 学段(学科群特有字段)
            + id: `123`(string,required) - 群学段的id
            + name: `小学`(string,required) - 群学段的名称
        + subject(object) - 学科(学科群特有字段)
            + id: `123`(string,required) - 群学科的id
            + name: `自然科学`(string,required) - 群学科的名称
        + role(enum,required) - 当前用户角色(1:群主,2:管理员,3:普通成员,4:不是本群成员)
            + Members
                + 1(number,required)
                + 2(number,required)
                + 3(number,required)
                + 4(number,required)
        + apply(enum,required) - 当前用户申请入群状态(1: 提交申请了，未审批，2: 拒绝申请(或之前都没有提交过申请)，3: 同意申请(直接进群了，isJoin为1))
            + Members
                + 1(number,required)
                + 2(number,required)
        + cover_bg_url: `http://covteam.u.qiniudn.com/poster.png`(string,required) - 群组背景图片


## 申请验证 [POST /group_apply]

申请入群

+ Request (application/json;charset=utf-8)
    + Attributes
        + group_id: `112121212`(string,required) - 群组的id
        + user_id: `11212121111`(string,required) - 当前的id(不需要可以忽略)
        + text: `申请的理由啊啊啊啊`(string,required) - 申请的理由

+ Response 201 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 操作是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息


## 解散该群 [POST /group_disband/{id}]

只有群主可以解散该群

+ Parameters
    + id: `112121212`(string,required) - 群组的id

+ Response 201 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 操作是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息

## 退群/管理员踢出群 [POST /group_logout]

成员可退群,管理员踢出群合并

+ Request (application/json;charset=utf-8)
    + Attributes
        + group_id: `112121212`(string,required) - 群组的id
        + user_id: `11212121111`(string,required) - 当前的id(不需要可以忽略)

+ Response 201 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 操作是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息


## 上传群头像 [POST /upload/avatar]

上传群头像新增一个借口

+ Request (application/json;charset=utf-8)
    + Attributes
          + attach: `1sdasdadsadczf`(string,required) - key参数

+ Response 201 (application/json;charset=utf-8)
    + Attributes
        + success(enum,required) - 操作是否成功(true/false)
            + Members
                + true(boolean,required)
                + false(boolean,required)
        + message: `添加成功`(string,required) - 操作返回信息
        + id: `123123`(string,required) - 图片id
        + name: `暮狼寻乡`(string,required) - 图片名字
        + type: `jpg`(string,required) - 图片格式
        + url: `http://www.baidu.com/xxx.jpg`(string,required) - 图片阅览地址
# Group 发现

## 获取发现下的热门群组 [GET /finds{?type,page,per_page}]

+ Parameters
    + type: `forum`(string,optional) - type区分获取发现的类别,forum代表群组
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + total_count: 100 (number,required) - 数据总数
        + data(array[object], fixed) - 所有群组
            + (object)
                + id: `1231231` (string,required) - 群组id
                + name: `xxx日历` (string,required) - 群组名字
                + created_at: `10月18日 17:56` - 该群组创建的时间
                + cover_image_url: `http:www.baidu.com/xxx.jpg` - 该群组头像图片
                + member: 100(number,required) - 成员人数
                + role(enum,required) - 当前用户在动态所在群的角色(1:群主,2:管理员,3:普通成员,4:不是本群成员)
                    + Members
                        + 1(number,required)
                        + 2(number,required)
                        + 3(number,required)
                        + 4(number,required)


## 获取发现下的热门话题 [GET /finds_topic{?type,page,per_page}]

:::warning
注意这里的接口全部都是finds,不是finds_topic,只是在一个文件中不能有同命名的接口,就该了一下，真正的是/finds?type=topic&page=1&per_page=10
:::

+ Parameters
    + type: `topic`(string,optional) - type区分获取发现的类别,topic代表话题
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + total_count: 100(number,required) - 话题总数
        + data(array[object],fixed) - 话题数据
            + (object)
                + id: `12312312312`(string,required) - 话题的id
                + name: `话题名称霹雳哗啦`(string,required) - 话题的名称
                + speak: 100(string,required) - 该话题发言总数
                + isTop(enum,required) - 是否置顶(1:置顶,2:不置顶)
                    + Members
                        + 1(number,required)
                        + 2(number,required)
                + group: `乐知行群组`(string,required) - 该话题所在的群组(不是群组话题传空)
                + role(enum,required) - 当前用户在动态所在群的角色(1:群主,2:管理员,3:普通成员,4:不是本群成员)
                    + Members
                        + 1(number,required)
                        + 2(number,required)
                        + 3(number,required)
                        + 4(number,required)
                + created_at: `2016-01-01`(string,required) - 该话题的创建时间
                + create: `李小龙`(string,required) - 该话题的发起者




## 获取发现下的热门发言 [GET /finds_essay{?type,page,per_page}]

:::warning
注意这里的接口全部都是finds,不是finds_essay,只是在一个文件中不能有同命名的接口,就该了一下，真正的是/finds?type=essay&page=1&per_page=10
:::

+ Parameters
    + type: `essay`(string,optional) - type区分获取发现的类别,essay代表发言
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + total_count: 100 (number,required) - 数据总数
        + data(array[object], fixed) - 所有动态
            + (object)
                + id: `123456` (string,required) - 动态id
                + group: `小学语文学科群` (string,required) - 动态发表所在群(个人发言传空)
                + role(enum,required) - 当前用户在动态所在群的角色(1:群主,2:管理员,3:普通成员,4:不是本群成员)
                    + Members
                        + 1(number,required)
                        + 2(number,required)
                        + 3(number,required)
                        + 4(number,required)
                + comments(object,required) - 动态评论数组(目前在首页只显示三条，详情中全部显示)
                    + total_count: 100 (number,required) - 所有动态评论总数
                    + data (array[object],fixed) - 动态评论的前三条
                        + (object)
                            + id: `9890`(string,required) - 评论id
                            + user(object,required) - 评论人的信息obj
                                + id: `231123`(string,required) - 评论人的id
                                + name: `周润发`(string,required) - 评论人的name
                                + profile_image_url: `http:www.baidu.com/xxx.jpg` - 评论人的头像图片地址
                            + reply(object,required) - 评论回复人信息obj
                                + id: `765665`(string,required) - 评论回复人的id
                                + name: `赌神`(string,required) - 评论回复人的名字
                            + created_at: `12秒前`(string,required) - 评论时间
                            + text: `霹雳哗啦评论的内容啊啊`(string,required) - 评论的内容
                            + pics(array[object],fixed) - 评论图片或回复图片数组
                                + (object)
                                    + name: `xxx`(string,required) - 评论图片或回复图片名字1
                                    + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片缩略图地址
                                    + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 评论图片或回复图片原图地址
                                    + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                                    + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + user(object,required) - 动态发表人信息对象
                    + id: `1111` (string,required) - 动态发表人id
                    + name: `王小二` (string,required) - 动态发表人name
                    + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 动态发表人头像地址
                + created_at: `10月18日 20:14` (string,required) - 动态发表时间
                + text: `霹雳哗啦动态内容` (string,required) - 动态内容
                + pics(array[object],fixed) - 动态相关图片数组
                    + (object)
                        + name: `xxx`(string,required) - 动态相关图片名字1
                        + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                        + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                        + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                        + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + retweeted(object,required) - 转发动态信息obj
                    + id: `1112212`(string,required) - 转发动态的id
                    + text: `霹雳哗啦转发动态的内容`(string,required) - 转发动态的内容
                    + created_at: `10月29日 15:10`(string,required) - 转发动态创建的时间
                    + user(object,required) - 转发动态发表人信息对象
                        + id: `1111222` (string,required) - 转发动态发表人id
                        + name: `王小三` (string,required) - 转发动态发表人name
                        + profile_image_url: `http:www.baidu.com/xxx.jpg` (string,required) - 转发动态发表人头像地址
                    + pics(array[object],fixed) - 动态相关图片数组
                        + (object)
                            + name: `xxx`(string,required) - 动态相关图片名字1
                            + thumb_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片缩略图地址
                            + original_url: `http:www.baidu.com/xxx.jpg`(string,required) - 动态相关图片原图地址
                            + width: `250`(string,required) - 原图宽度(好像是的，之前的api文档中没有，看线上请求的)
                            + height: `250`(string,required) - 原图高度(好像是的，之前的api文档中没有，看线上请求的)
                + likes(object,required) - 动态点赞信息obj
                    + total_count: 22 (number,required) - 动态点赞人的总数
                    + love(enum,required) - 自己是不是点了赞 1表示已点赞0表示未点赞
                        + Members
                            + 1(number,required)
                            + 0(number,required)
                    + data(array[object],fixed) - 点赞人信息obj
                        + (object)
                            + id: `111222333`(string,required) - 点赞人id
                            + name: `李小龙`(string,required) - 点赞人姓名


## 获取发现下的人群教师 [GET /finds_teacher{?type,page,per_page}]

:::warning
注意这里的接口全部都是finds,不是finds_teacher,只是在一个文件中不能有同命名的接口,就该了一下，真正的是/finds?type=teacher&page=1&per_page=10
:::

+ Parameters
    + type: `teacher`(string,optional) - type区分获取发现的类别,teacher代表教师
    + page: 1 (number,optional) - 获取数据第几页
    + per_page: 10 (number,optional) - 每页获取多少条数据

+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + total_count: 100 (number,required) - 数据总数
        + data(array[object], fixed) - 所有群组
            + (object)
                + id: `1231231` (string,required) - 教师id
                + name: `李小龙` (string,required) - 教师名字
                + cover_image_url: `http:www.baidu.com/xxx.jpg`(string,required) - 教师头像图片
                + isFollow(enum,required) - 是否已经关注
                    + Members
                        + 1(number,required)
                        + 2(number,required)
